"""initial migration

Revision ID: 41bba3352edd
Revises: 
Create Date: 2023-08-09 00:55:32.158229

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '41bba3352edd'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_category_name', ['name'])  # Provide a name here

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('uq_category_name', type_='unique')  # Provide the same name used in upgrade

    # ### end Alembic commands ###

